### ISSUE TITLE
Missing Language Configuration

### ISSUE THREAD

**Issue by medienbaecker** [cajames/kirby-editor-gallery-block#1]
![image](https://user-images.githubusercontent.com/7975568/84914285-bb8a5700-b0bb-11ea-8a87-7c51321db0f3.png)

```php
# i18n/en.php
'editor.blocks.gallery.settings.imageAlt.label' => 'Gallery Alt Name',
```

**Comment by cajames** [comment]
I realised I've actually not used this setting as it's difficult to set alt text on gallery of images. Any thoughts on what this could be?

Options are some sort of gallery caption, or to remove this setting.

**Comment by cajames** [comment]
Actually I just realised I've missed a few more items in the translations, let me add those too. :) @medienbaecker Hope you'd be able to help me with the German translations for those

**Comment by medienbaecker** [comment]
Thanks for adding the missing items! ❤️
One thing that's still untranslated is the "or" between "Upload images" and "Select images".

**Comment by cajames** [comment]
Ah yes, great point! I'll reopen this until all the fixes are in. :)
