### ISSUE TITLE
can't access property "open"

### ISSUE THREAD

**Issue by mynameisfreedom** [cajames/kirby-editor-gallery-block#13]
Hi, @cajames, thank you for creating this beautiful plugin. 
I especially love your snippet width math, it is a masterpiece. :-)

But there is an issue in the editor every time when I try to delete gallery block

`can't access property "open", this.$refs.settings is undefined`

![Screenshot_2020-06-24 Tips For Camera Protection While Travelling Zero One Kirby CMS Theme](https://user-images.githubusercontent.com/46815297/85531858-6bf1e100-b60f-11ea-9eac-f82fd0069f1a.png)

How to reproduce: 
I added 7 images, they went to 4 rows.
When I try to delete rows from the bottom one, this happens every time on the second one from the bottom.

**Comment by cajames** [comment]
Hey @mynameisfreedom, ah thank you for picking this up! I think I've found the issue and will ship a fix soon.

**Comment by cajames** [comment]
@mynameisfreedom Please let me know if you're still facing this issue with the latest version. 😊

**Comment by mynameisfreedom** [comment]
Hi, @cajames !

Confirmed, the issue is resolved.

Thank you very much!
